resources:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/baremetal/deploy.yaml

# 프로메테우스가 가능하도록 patch 추가
patches:
- path: append_prometheus_service.yaml
  target:
    kind: Service
    name: ingress-nginx-controller
- path: append_prometheus_deployment.yaml
  target:
    kind: Deployment
    name: ingress-nginx-controller
