apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - image: bitnami/influxdb:1.8.5
        imagePullPolicy: Always
        name: influxdb
        ports:
        - containerPort: 8086
        env:
          - name: INFLUXDB_ADMIN_USER_PASSWORD
            value: test
          - name: INFLUXDB_ADMIN_USER_TOKEN
            value: test
          - name: INFLUXDB_HTTP_AUTH_ENABLED
            value: "false"
          - name: INFLUXDB_DB
            value: entto
