apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metric-kustomization

resources:
- github.com/kubernetes/ingress-nginx/deploy/grafana
- service.yaml
- ingress.yaml
- deployment.yaml
- issuer.yaml
