apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: application-kustomization
commonLabels:
  createdby: argocd

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- pv.yaml
- pvc.yaml

generatorOptions:
  disableNameSuffixHash: true
images:
- name: sororiri/entto-backend
  newTag: eb46550
