apiVersion: v1
kind: PersistentVolume
metadata:
  name: entto-nfs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/sori/db/entto
    server: 192.168.0.182
