apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: entto
    repoURL: "https://github.com/SangYunLeee/argocd-enttolog.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true