apiVersion: v1
kind: Service
metadata:
  name: mysql-prod
  namespace: storage
spec:
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30306
    protocol: TCP
  selector:
    app: mysql
    use: production
  type: NodePort
