apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: storage
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      use: production
  template:
    metadata:
      labels:
        app: mysql
        use: production
    spec:
      containers:
        - name: mysql-container
          image: mysql:8
          envFrom:
            - secretRef:
                name: sql-secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: config-volume
              mountPath: /etc/mysql/conf.d
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "2Gi"
              cpu: "3"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role-mysql
                    operator: Exists
      volumes:
        - name: mysql-persistent-storage
          hostPath:
            path: /k8s/var/lib/mysql_
        - name: config-volume
          configMap:
            name: mysql-config
