kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-opensearch-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensearch-pv-volume-0
  labels:
    type: local
spec:
  storageClassName: local-opensearch-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/opensearch
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sub
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensearch-pv-volume-1
  labels:
    type: local
spec:
  storageClassName: local-opensearch-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/opensearch
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sub2
