apiVersion: v1
kind: Service
metadata:
  name: postgres-prd
  namespace: storage
spec:
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30432
    protocol: TCP
  selector:
    app: postgres-prd
  type: NodePort
