apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-prd
  namespace: storage
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-prd
  template:
    metadata:
      labels:
        app: postgres-prd
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: dltkddbs12
          - name: POSTGRES_DB
            value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1500m"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: db
                    operator: Exists
      volumes:
        - name: data
          hostPath:
            path: /k8s/db/postgres/data