apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metric-application
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: metric
    repoURL: "https://github.com/SangYunLeee/argocd-enttolog.git"
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
