project: default
destination:
  server: 'https://kubernetes.default.svc'
  namespace: monitoring
syncPolicy:
  syncOptions:
    - CreateNamespace=true
sources:
  - repoURL: 'https://github.com/SangYunLeee/devops-package.git'
    path: prometheus-stack/helm
    targetRevision: HEAD
    directory:
      recurse: true
