apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-application
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - repoURL: >-
        https://sangyunleee.github.io/devops-package/prometheus-stack/charts/stable
      targetRevision: 0.1.3
      chart: prometheus-stack
      helm:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
