apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  replicas: {{ .Values.backend.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
        tier: backend
    spec:
      containers:
      - image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: Always
        name: {{ .Values.backend.name }}
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: entto-secret-1
        volumeMounts:
          - name: entto-mount
            mountPath: /app/uploads_
        resources:
          requests:
            memory: "400Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
      volumes:
      - name: entto-mount
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
      - image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: Always
        name: {{ .Values.frontend.name }}
        ports:
        - containerPort: 80
