apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  built-by: setup-env
namespace: argocd
resources:
- argocd-namespace.yaml
# argoCD yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
- path: fix_argocd_health_check.yaml
  target:
    kind: ConfigMap
    name: argocd-cm

- path: add_guest_user.yaml
  target:
    kind: ConfigMap
    name: argocd-cm

- path: add_guest_password.yaml
  target:
    kind: Secret
    name: argocd-secret

- path: set_default_user_role.yaml
  target:
    kind: ConfigMap
    name: argocd-rbac-cm
