apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  built-by: setup-env
namespace: argocd
resources:
- argocd-namespace.yaml
# argoCD yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
