apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.backend.name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.ingress.backend.host }}
    secretName: {{ .Values.ingress.backend.host }}-tls
  rules:
  - host: {{ .Values.ingress.backend.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.frontend.name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.ingress.frontend.host }}
    secretName: www-entto-shop-tls
  rules:
  - host: {{ .Values.ingress.frontend.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.name }}
            port:
              number: 80
