apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  accessModes:
    - ReadWriteMany
  volumeName: {{ .Values.pv.name }}
  resources:
    requests:
      storage: 10Gi
