# nginx-ingress-controller 와 cert-manager 가 설치되어 있어야 함
apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

resources:
- application.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: entto-secret-1
  envs:
  - .env
